// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKpiHmy5nVtWxpu24Y3XvcbnREu_mMVo',
    appId: '1:569368415578:android:3f70c1d6eaf0bc133ff763',
    messagingSenderId: '569368415578',
    projectId: 'chatter-ce1d0',
    databaseURL: 'https://chatter-ce1d0-default-rtdb.firebaseio.com',
    storageBucket: 'chatter-ce1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUBZQjLtYDzrS-98DKKQlDB2bDM864sA',
    appId: '1:569368415578:ios:46e7aed13efad7a23ff763',
    messagingSenderId: '569368415578',
    projectId: 'chatter-ce1d0',
    databaseURL: 'https://chatter-ce1d0-default-rtdb.firebaseio.com',
    storageBucket: 'chatter-ce1d0.appspot.com',
    iosClientId: '569368415578-572lf8gnns3r5gfpn84gi51m0ua4eb8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultationrecord',
  );
}
